# Generated by Django 5.1.2 on 2025-03-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
                ("payment_date", models.DateTimeField()),
                ("stripe_charge_id", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="logo_images/"),
                ),
                ("contact_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("tuition_fee", models.DecimalField(decimal_places=2, max_digits=11)),
                ("duration", models.CharField()),
                ("start_date", models.DateField()),
                ("website", models.URLField(blank=True, null=True)),
                ("country", models.CharField(blank=True, null=True)),
                ("language", models.CharField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_program_s",
                        to="mainapp.category",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="university_program_s",
                        to="mainapp.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_programapplication_s",
                        to="mainapp.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_programsubmission_s",
                        to="mainapp.payment",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_programsubmission_s",
                        to="mainapp.program",
                    ),
                ),
            ],
        ),
    ]
